### ISSUE TITLE
使用许可

### ISSUE THREAD

**Issue by yurihuruitao** [DNLINYJ/Biilibili_All_Danmu#1]
尊敬的作者，您好，我想将您的这个项目运用于社会语言学（主要是网络用语方面）课程论文的数据获取，仅用于学习交流，不用做商业用途，可以允许吗？
另外，报告一个小bug，您的项目的根目录下少建立了一个名为sqlite3的空文件夹，在运行时会报错，建议修复。

**Comment by DNLINYJ** [comment]
只要不是商业用途，个人是可以免费使用的，对于sqlite3文件夹不存在的问题，请将报错信息一并发到Issues，以便进行修复。
